# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  username: postgres
  host: localhost
  password: 'ho'

development:
  <<: *default
  database: secure_route_development 

test:
  <<: *default
  database: secure_route_test

production:
  <<: *default
  database: secure_route
