# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b333905e2b53ba3053f368329e5e8a03250211ec2e69e6993c85cf9d597e12024636ba4ab8c46e007bb69e8aa2ef0c32df0ccc5a002715c15deda38b2c450af9

test:
  secret_key_base: 30d978a9c2203352a11df084a99410009b413cb2ab790b7b0ac18f407a8ead72fb7ef8abfb7e8a853c4ecde70ed086c2461fb07907acc9082648aa617de82cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
